name: Build OpenSSL and Update Project

on:
  workflow_dispatch:

jobs:
  build-openssl:
    name: Build OpenSSL for Linux and Windows
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential mingw-w64          

      - name: Create branch for OpenSSL binaries
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b add-openssl-binaries
      - name: Download OpenSSL source
        run: |
          curl -O https://www.openssl.org/source/openssl-1.1.1.tar.gz
          tar -xzf openssl-1.1.1.tar.gz
          mv openssl-1.1.1 openssl-src
      
      - name: Build OpenSSL for Linux
        run: |
          cd openssl-src
          ./config no-shared --prefix=$GITHUB_WORKSPACE/openssl/linux_x86-64
          make -j$(nproc)
          make install

      - name: Build OpenSSL for Windows (64-bit)
        run: |
          cd openssl-src
          ./Configure mingw64 no-shared --prefix=$GITHUB_WORKSPACE/openssl/windows_x86-64
          make -j$(nproc) CC=x86_64-w64-mingw32-gcc
          make install

      - name: Commit and create PR for OpenSSL binaries
        run: |
          git add openssl/
          git commit -m "Add OpenSSL 1.1.1 binaries for Linux and Windows"
          git push origin add-openssl-binaries
          gh pr create --title "Add OpenSSL 1.1.1 binaries" --body "This PR adds the compiled OpenSSL 1.1.1 binaries for Linux and Windows." --base feature-openssl-update
