name: Hello World

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'Devlab'
        type: choice
        options:
          - Production
          - Preproduction
          - Staging
          - Devlab
jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Say Hello
      run: echo "Hello, World!"
