name: Manual application installation

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Please select above the branch or tag.\n\nWhat environment do you want to install to?\nPlease choose one of the following options:\n Production, Preproduction, Staging, Devlab.'
        required: true
        default: 'Devlab'
        type: choice
        options:
          - Production
          - Preproduction
          - Staging
          - Devlab

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}  # Use the ref selected by the user
        
      - name: Print Environment
        run: echo "Selected Environment ${{ github.event.inputs.environment }}"
