name: Manual application installation

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'What environment do you want to install to? Please choose one of the following options: Production, Preproduction, Staging, Devlab. This will determine the environment in which the workflow will run.'
        required: true
        default: 'Devlab'
        type: choice
        options:
          - Production
          - Preproduction
          - Staging
          - Devlab

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print Environment
        run: echo "Selected Environment ${{ github.event.inputs.environment }}"
